Models/ErrorViewModel.cs
using System;

namespace School_Management.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SchoolContext.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace School_Management.Models
{
    public class SchoolContext : DbContext
    {
        public DbSet<StudentModel> Students { get; set; }
        public DbSet<TeacherModel> Teachers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=school.db");
    }
}

Models/StudentModel.cs
namespace School_Management.Models
{
    public class StudentModel
    {
        public int ID {get; set;}
        public string name {get; set;}
        public int roll{get; set;}
        public int classNO{get; set;}
    }
}

Models/TeacherModel.cs
namespace School_Management.Models
{
    public class TeacherModel
    {
        public int ID{get; set;}
        public string name{get; set;}
        public string designation{get; set;}
        public string institute{get; set;}
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using School_Management.Models;

namespace School_Management.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using School_Management.Models;
using School_Management.Service;
using System.Collections.Generic;

namespace School_Management.Controllers
{
    public class StudentController : Controller
    {
        public IStudentService studentService;
        public StudentController(IStudentService studentService){
            this.studentService = studentService;
        }

        public IActionResult addStudent(){
            return View();
        }

        [HttpPost]
        public IActionResult saveStudent(StudentModel student){
            studentService.saveStudent(student);
            return Redirect("index");
        }

        public IActionResult index(){
            List<StudentModel> allStudent =  studentService.getStudents();
            return View(allStudent);
        }

        public IActionResult deleteStudent(StudentModel student){
            studentService.deleteStudent(student);
            return Redirect("index");
        }

        public IActionResult editStudent(StudentModel student){
            return View(student);
        }

        [HttpPost]
        public IActionResult updateStudent(StudentModel student){
            studentService.updateStudent(student);
            return Redirect("index");
        }
    }
}

Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using School_Management.Models;
using System.Collections.Generic;
using School_Management.Service;

namespace School_Management.Controllers
{
    public class TeacherController : Controller
    {
        public ITeacherService teacherService;
        public TeacherController(ITeacherService teacherService){
            this.teacherService = teacherService;
        }
         public IActionResult addTeacher(){
            return View();
        }
        [HttpPost]
        public IActionResult saveTeacher(TeacherModel teacher){
            teacherService.saveTeacher(teacher);
            return Redirect("teacherHome");
        }
        public IActionResult teacherHome(){
            List<TeacherModel> allTeacher  = teacherService.getTeachers();
            return View(allTeacher);
        }
        public IActionResult deleteTeacher(TeacherModel teacher){
            teacherService.deleteTeacher(teacher);
            return Redirect("teacherHome");
        }
        public IActionResult editTeacher(TeacherModel teacher){
            return View(teacher);
        }
        [HttpPost]
        public IActionResult updateTeacher(TeacherModel teacher){
            teacherService.updateTeacher(teacher);
            return Redirect("teacherHome");
        }   
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School_Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="addStudent">Add Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="teacherHome">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="addTeacher">Add Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - School_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Student/addStudent.cshtml
@{
    ViewData["Title"] = "Add New Student";
}

<h3>Add New Student</h3>

<form action="saveStudent" method="POST">
    <input type="text" name="name" placeholder="Enter Student's Name"> <br>
    <input type="text" name="roll" placeholder="Enter Student's Roll"> <br>
    <input type="text" name="classNO" placeholder="Enter Student's Class"> <br>
    <input type="submit" name="Save Student" >
</form>

Views/Student/editStudent.cshtml
@model School_Management.Models.StudentModel;

@{
    ViewData["Title"] = "Update Student";
}

<h3>Update @Model.name</h3>

<form  asp-controller="Student" asp-action="updateStudent" method="POST">
    <input type="hidden" value="@Model.ID" name="ID"> <br>
    <input type="text" name="name" placeholder="Enter Student's Name"> <br>
    <input type="text" name="roll" placeholder="Enter Student's Roll"> <br>
    <input type="text" name="classNO" placeholder="Enter Student's Class"> <br>
    <input type="submit" name="Update Student" >
</form>

Views/Student/index.cshtml
@model IEnumerable<School_Management.Models.StudentModel>

@{
    ViewData["Title"] = "WelCome Here";
}

<h3>Student's List</h3>

<table border="1" style="width: 50%; " align="center">
    <tr>
        <th>Serial No</th>
        <th>Name</th>
        <th>Roll</th>
        <th>Class No</th>
        <th>Action</th>
    </tr>

@foreach (var student in Model)
{
    <tr>
        <td>@student.ID</td>
        <td>@student.name</td>
        <td>@student.roll</td>
        <td>@student.classNO</td>
        <td>
            @Html.ActionLink("Delete", "deleteStudent", "Student", @student) 
            @Html.ActionLink("Edit", "editStudent", "Student", @student)
        </td>

    </tr>
}

</table>

Views/Student/updateStudent.cshtml
@model School_Management.Models.StudentModel

@{
    ViewData["Title"] = "update";
}

 <h2>@Model.name</h2>

Views/Teacher/addTeacher.cshtml
@{
    ViewData["Title"] = "Add New Teacher";
}

<h3>Add New Student</h3>

<form action="saveTeacher" method="POST">
    <input type="text" name="name" placeholder="Enter Teacher's Name"> <br>
    <input type="text" name="designation" placeholder="Enter Teacher's Designation"> <br>
    <input type="text" name="institute" placeholder="Enter Institute"> <br>
    <input type="submit" name="Save Teacher" >
</form>

Views/Teacher/editTeacher.cshtml
@model School_Management.Models.TeacherModel

@{
    ViewData["Title"] = "Update Teacher";  
}

<h4>Update @Model.name</h4>

<form asp-controller="Teacher" asp-action="updateTeacher" method="POST">
    <input type="hidden" name="ID" value="@Model.ID"> 
    <input type="text" name="name" placeholder="Enter Teacher's Name"> <br>
    <input type="text" name="designation" placeholder="Enter Teacher's Designation"> <br>
    <input type="text" name="institute" placeholder="Enter Institute"> <br>
    <input type="submit" name="Update Teacher" >
</form>

Views/Teacher/teacherHome.cshtml
@model IEnumerable<School_Management.Models.TeacherModel>

@{
    ViewData["Title"] = "WelCome Here";
}

<h3>Teacher's List</h3>

<table border="1" style="width: 50%; " align="center">
    <tr>
        <th>Serial No</th>
        <th>Name</th>
        <th>Designation</th>
        <th>Institute</th>
        <th>Action</th>
    </tr>

@foreach (var teacher in Model)
{
    <tr>
        <td>@teacher.ID</td>
        <td>@teacher.name</td>
        <td>@teacher.designation</td>
        <td>@teacher.institute</td>
        <td>
            @Html.ActionLink("Delete", "deleteTeacher", "Teacher", @teacher)
            @Html.ActionLink("Edit", "editTeacher", "Teacher", @teacher)
        </td>
    </tr>
}

</table>